provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Environment = var.environment
      Owner       = var.owner
      Project     = var.project_name
      ManagedBy   = "terraform"
    }
  }
}

data "aws_caller_identity" "current" {}

data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

# -------------------------------------------------------
# EC2 KEY PAIR — generated by Terraform, written locally
# -------------------------------------------------------
resource "tls_private_key" "compliance" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "compliance" {
  key_name   = var.key_name
  public_key = tls_private_key.compliance.public_key_openssh

  tags = {
    Name = "${var.project_name}-key"
  }
}

resource "local_file" "private_key" {
  content         = tls_private_key.compliance.private_key_pem
  filename        = "${path.module}/../compliance-key.pem"
  file_permission = "0600"
}

# -------------------------------------------------------
# SECURITY GROUP — SSH from your current IP only
# -------------------------------------------------------
data "http" "my_ip" {
  url = "https://checkip.amazonaws.com"
}

resource "aws_security_group" "compliance_targets" {
  name        = "${var.project_name}-targets-sg"
  description = "Security group for compliance scan targets"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH from runner IP only"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["${chomp(data.http.my_ip.response_body)}/32"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.project_name}-targets-sg"
  }
}

# -------------------------------------------------------
# IAM ROLE — SSM and CloudWatch access for EC2 instances
# -------------------------------------------------------
resource "aws_iam_role" "compliance_target" {
  name = "${var.project_name}-target-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.compliance_target.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_role_policy_attachment" "cloudwatch" {
  role       = aws_iam_role.compliance_target.name
  policy_arn = "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
}

resource "aws_iam_instance_profile" "compliance_target" {
  name = "${var.project_name}-target-profile"
  role = aws_iam_role.compliance_target.name
}

# -------------------------------------------------------
# AMAZON LINUX 2023 — compliance target instance
# -------------------------------------------------------
data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

resource "aws_instance" "amazon_linux" {
  ami                    = data.aws_ami.amazon_linux_2023.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.compliance.key_name
  subnet_id              = data.aws_subnets.default.ids[0]
  vpc_security_group_ids = [aws_security_group.compliance_targets.id]
  iam_instance_profile   = aws_iam_instance_profile.compliance_target.name
  monitoring             = true

  root_block_device {
    volume_type = "gp3"
    volume_size = 20
    encrypted   = true
  }

  metadata_options {
    http_tokens = "required"
  }

  user_data = base64encode(<<-EOF
    #!/bin/bash
    dnf update -y
    dnf install -y openscap-scanner scap-security-guide python3-pip
    pip3 install boto3
    mkdir -p /opt/compliance-reports
    chmod 755 /opt/compliance-reports
  EOF
  )

  tags = {
    Name             = "${var.project_name}-amazon-linux-2023"
    OS               = "amazon-linux-2023"
    ComplianceTarget = "true"
    CISProfile       = "level1-level2"
  }
}

# -------------------------------------------------------
# UBUNTU 22.04 — compliance target instance
# -------------------------------------------------------
data "aws_ami" "ubuntu_2204" {
  most_recent = true
  owners      = ["099720109477"]

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

resource "aws_instance" "ubuntu" {
  ami                    = data.aws_ami.ubuntu_2204.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.compliance.key_name
  subnet_id              = data.aws_subnets.default.ids[0]
  vpc_security_group_ids = [aws_security_group.compliance_targets.id]
  iam_instance_profile   = aws_iam_instance_profile.compliance_target.name
  monitoring             = true

  root_block_device {
    volume_type = "gp3"
    volume_size = 20
    encrypted   = true
  }

  metadata_options {
    http_tokens = "required"
  }

  user_data = base64encode(<<-EOF
    #!/bin/bash
    apt-get update -y
    apt-get install -y libopenscap8 ssg-base ssg-debderived \
      ssg-debian ssg-nondebian python3-pip python3-boto3
    mkdir -p /opt/compliance-reports
    chmod 755 /opt/compliance-reports
  EOF
  )

  tags = {
    Name             = "${var.project_name}-ubuntu-2204"
    OS               = "ubuntu-2204"
    ComplianceTarget = "true"
    CISProfile       = "level1-level2"
  }
}

# -------------------------------------------------------
# SNS TOPIC — compliance alert notifications
# -------------------------------------------------------
resource "aws_sns_topic" "compliance_alerts" {
  name = "${var.project_name}-alerts"

  tags = {
    Name = "${var.project_name}-alerts"
  }
}

resource "aws_sns_topic_subscription" "email" {
  topic_arn = aws_sns_topic.compliance_alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# -------------------------------------------------------
# CLOUDWATCH DASHBOARD
# -------------------------------------------------------
resource "aws_cloudwatch_dashboard" "compliance" {
  dashboard_name = "${var.project_name}-compliance-dashboard"

  dashboard_body = jsonencode({
    widgets = [
      {
        type   = "metric"
        x      = 0
        y      = 0
        width  = 12
        height = 6
        properties = {
          title   = "Compliance Score by Instance"
          view    = "timeSeries"
          stacked = false
          metrics = [
            ["ComplianceScanner", "ComplianceScore",
              "InstanceId", aws_instance.amazon_linux.id,
              "Profile", "cis-level1",
              { label = "AL2023 CIS L1", stat = "Average" }
            ],
            ["ComplianceScanner", "ComplianceScore",
              "InstanceId", aws_instance.amazon_linux.id,
              "Profile", "cis-level2",
              { label = "AL2023 CIS L2", stat = "Average" }
            ],
            ["ComplianceScanner", "ComplianceScore",
              "InstanceId", aws_instance.ubuntu.id,
              "Profile", "cis-level1",
              { label = "Ubuntu CIS L1", stat = "Average" }
            ],
            ["ComplianceScanner", "ComplianceScore",
              "InstanceId", aws_instance.ubuntu.id,
              "Profile", "cis-level2",
              { label = "Ubuntu CIS L2", stat = "Average" }
            ]
          ]
          period = 3600
          region = var.aws_region
          yAxis  = { left = { min = 0, max = 100 } }
          annotations = {
            horizontal = [{
              value = var.compliance_threshold
              label = "Threshold (${var.compliance_threshold}%)"
              color = "#ff0000"
            }]
          }
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 0
        width  = 12
        height = 6
        properties = {
          title   = "Findings Count by Severity"
          view    = "timeSeries"
          stacked = true
          metrics = [
            ["ComplianceScanner", "CriticalFindings",
              { label = "Critical", color = "#d62728" }
            ],
            ["ComplianceScanner", "HighFindings",
              { label = "High", color = "#ff7f0e" }
            ],
            ["ComplianceScanner", "MediumFindings",
              { label = "Medium", color = "#bcbd22" }
            ]
          ]
          period = 3600
          region = var.aws_region
        }
      }
    ]
  })
}

# -------------------------------------------------------
# CLOUDWATCH ALARM — score drops below threshold
# -------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "compliance_below_threshold" {
  alarm_name          = "${var.project_name}-score-below-threshold"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = 1
  metric_name         = "ComplianceScore"
  namespace           = "ComplianceScanner"
  period              = 3600
  statistic           = "Minimum"
  threshold           = var.compliance_threshold
  alarm_description   = "Compliance score dropped below ${var.compliance_threshold}%"
  treat_missing_data  = "notBreaching"
  alarm_actions       = [aws_sns_topic.compliance_alerts.arn]
  ok_actions          = [aws_sns_topic.compliance_alerts.arn]

  tags = {
    Name = "${var.project_name}-compliance-alarm"
  }
}
