#!/usr/bin/env python3
"""
Compliance HTML Report Generator
Generates a consolidated HTML report from all compliance scan results.

Usage:
    python3 scripts/generate-report.py \
        --reports-dir reports \
        --output reports/consolidated-report.html \
        --threshold 85
"""

import argparse
import glob
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import defusedxml.ElementTree as ET
except ImportError:
    import xml.etree.ElementTree as ET  # noqa: S405

NS = {"xccdf": "http://checklists.nist.gov/xccdf/1.2"}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CIS Compliance Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 20px;
           background: #0a0a0a; color: #e0e0e0; }}
    h1 {{ color: #00FFB2; }}
    h2 {{ color: #4CC9F0; border-bottom: 1px solid #333; padding-bottom: 6px; }}
    .summary {{ display: flex; gap: 20px; flex-wrap: wrap; margin: 20px 0; }}
    .card {{ background: #1a1a2e; border-radius: 8px; padding: 20px; min-width: 180px; }}
    .score {{ font-size: 2em; font-weight: bold; }}
    .pass {{ color: #00FFB2; }}
    .fail {{ color: #ff4444; }}
    table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
    th {{ background: #1a1a2e; padding: 10px; text-align: left; color: #4CC9F0; }}
    td {{ padding: 8px 10px; border-bottom: 1px solid #333; }}
    tr:hover {{ background: #1a1a2e; }}
    .badge {{ padding: 3px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold; }}
    .badge-pass {{ background: #00FFB2; color: #000; }}
    .badge-fail {{ background: #ff4444; color: #fff; }}
    .footer {{ margin-top: 40px; padding-top: 20px;
               border-top: 1px solid #333; color: #666; font-size: 0.9em; }}
  </style>
</head>
<body>
  <h1>&#127697; CIS Compliance Report</h1>
  <p>Generated: {generated_at}</p>
  <p>Project: openscap-ansible-compliance | Author: Emmanuel Ubani</p>

  <h2>Executive Summary</h2>
  <div class="summary">
    <div class="card">
      <div>Instances Scanned</div>
      <div class="score">{total_instances}</div>
    </div>
    <div class="card">
      <div>Avg CIS L1 Score</div>
      <div class="score {l1_class}">{avg_l1:.1f}%</div>
    </div>
    <div class="card">
      <div>Avg CIS L2 Score</div>
      <div class="score {l2_class}">{avg_l2:.1f}%</div>
    </div>
    <div class="card">
      <div>Critical Findings</div>
      <div class="score {critical_class}">{total_critical}</div>
    </div>
    <div class="card">
      <div>Gate Status</div>
      <div class="score {gate_class}">{gate_status}</div>
    </div>
  </div>

  <h2>Instance Details</h2>
  <table>
    <tr>
      <th>Instance</th><th>OS</th><th>CIS L1</th><th>CIS L2</th>
      <th>Critical</th><th>High</th><th>Medium</th><th>Gate</th>
    </tr>
    {instance_rows}
  </table>

  <div class="footer">
    <p>Report generated by openscap-ansible-compliance pipeline</p>
    <p>GitHub: github.com/Eaglewings966/openscap-ansible-compliance</p>
  </div>
</body>
</html>"""


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate consolidated HTML compliance report"
    )
    parser.add_argument("--reports-dir", default="reports")
    parser.add_argument("--output", default="reports/consolidated-report.html")
    parser.add_argument("--threshold", type=float, default=85.0)
    return parser.parse_args()


def safe_output_path(output_arg):
    """
    Resolve and validate the output path to prevent path traversal (CWE-22).
    The resolved path must stay within the current working directory tree.
    """
    base = Path(os.getcwd()).resolve()
    resolved = Path(output_arg).resolve()
    try:
        resolved.relative_to(base)
    except ValueError:
        print(f"ERROR: Output path '{output_arg}' resolves outside the project "
              f"directory. Aborting to prevent path traversal.")
        sys.exit(1)
    return resolved


def load_json_reports(reports_dir):
    reports = []
    for path in glob.glob(
        os.path.join(reports_dir, "**", "compliance-summary.json"), recursive=True
    ):
        try:
            with open(path) as fh:
                reports.append(json.load(fh))
        except Exception:
            pass
    return reports


def load_xml_reports(reports_dir):
    """Fallback: derive reports from raw XCCDF XML result files."""
    reports = []
    for path in glob.glob(
        os.path.join(reports_dir, "**", "*-results.xml"), recursive=True
    ):
        try:
            tree = ET.parse(path)
            root = tree.getroot()
            host = (
                root.findtext(".//xccdf:target", namespaces=NS)
                or Path(path).stem
            )
            rules = root.findall(".//xccdf:rule-result", namespaces=NS)
            passed = sum(
                1 for r in rules
                if r.findtext("xccdf:result", namespaces=NS) == "pass"
            )
            score = round(passed / len(rules) * 100, 1) if rules else 0
            reports.append({
                "hostname": host,
                "os": "unknown",
                "cis_level1_score": score,
                "cis_level2_score": score,
                "critical_findings": 0,
                "high_findings": 0,
                "medium_findings": 0,
            })
        except Exception:
            pass
    return reports


def build_rows(reports, threshold):
    rows = ""
    for r in reports:
        l2 = r.get("cis_level2_score", 0)
        passed = l2 >= threshold
        badge = "badge-pass" if passed else "badge-fail"
        label = "PASS" if passed else "FAIL"
        rows += (
            f"<tr>"
            f"<td>{r.get('hostname', 'unknown')}</td>"
            f"<td>{r.get('os', 'unknown')}</td>"
            f"<td>{r.get('cis_level1_score', 0):.1f}%</td>"
            f"<td>{r.get('cis_level2_score', 0):.1f}%</td>"
            f"<td style='color:#ff4444'>{r.get('critical_findings', 0)}</td>"
            f"<td style='color:#ffbb00'>{r.get('high_findings', 0)}</td>"
            f"<td>{r.get('medium_findings', 0)}</td>"
            f"<td><span class='badge {badge}'>{label}</span></td>"
            f"</tr>"
        )
    return rows


def main():
    args = parse_args()
    output_path = safe_output_path(args.output)

    reports = load_json_reports(args.reports_dir)
    if not reports:
        print("No JSON summary files found — falling back to XML result files...")
        reports = load_xml_reports(args.reports_dir)

    if not reports:
        print("No compliance reports found.")
        return

    avg_l1 = sum(r.get("cis_level1_score", 0) for r in reports) / len(reports)
    avg_l2 = sum(r.get("cis_level2_score", 0) for r in reports) / len(reports)
    total_critical = sum(r.get("critical_findings", 0) for r in reports)
    gate_pass = avg_l2 >= args.threshold and total_critical == 0

    html = HTML_TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        total_instances=len(reports),
        avg_l1=avg_l1,
        avg_l2=avg_l2,
        l1_class="pass" if avg_l1 >= args.threshold else "fail",
        l2_class="pass" if avg_l2 >= args.threshold else "fail",
        total_critical=total_critical,
        critical_class="pass" if total_critical == 0 else "fail",
        gate_status="PASS" if gate_pass else "FAIL",
        gate_class="pass" if gate_pass else "fail",
        instance_rows=build_rows(reports, args.threshold),
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    print(f"Report written to: {output_path}")


if __name__ == "__main__":
    main()
